"""add_ic_memo_and_signoff_tables

Revision ID: 045d88a5f87a
Revises: 3e204c7c3579
Create Date: 2026-08-05 17:31:25.359857

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "045d88a5f87a"
down_revision: str | None = "3e204c7c3579"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ic_memos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deal_id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("fund_entity_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("content_md", sa.Text(), nullable=True),
        sa.Column("final_signoff_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deal_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fund_entity_id"],
            ["fund_entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deal_id", "version", name="uq_ic_memos_deal_version"),
    )
    op.create_index(op.f("ix_ic_memos_deal_id"), "ic_memos", ["deal_id"], unique=False)
    op.create_index("ix_ic_memos_pm_created", "ic_memos", ["pm_id", "created_at"], unique=False)
    op.create_table(
        "ic_signoffs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("memo_id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("fund_entity_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("signature_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fund_entity_id"],
            ["fund_entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["memo_id"],
            ["ic_memos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("memo_id", "pm_id", name="uq_ic_signoffs_memo_pm"),
    )
    op.create_index(
        "ix_ic_signoffs_memo_created", "ic_signoffs", ["memo_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_ic_signoffs_memo_id"), "ic_signoffs", ["memo_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ic_signoffs_memo_id"), table_name="ic_signoffs")
    op.drop_index("ix_ic_signoffs_memo_created", table_name="ic_signoffs")
    op.drop_table("ic_signoffs")
    op.drop_index("ix_ic_memos_pm_created", table_name="ic_memos")
    op.drop_index(op.f("ix_ic_memos_deal_id"), table_name="ic_memos")
    op.drop_table("ic_memos")
    # ### end Alembic commands ###
