"""add_connector_persona_interactive_compliance_tables

Revision ID: 05bee0ba72de
Revises: 2163db3ebe42
Create Date: 2026-08-06 15:04:15.066665

"""

from collections.abc import Sequence

import sqlalchemy as sa

import axe.security.encryption
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05bee0ba72de"
down_revision: str | None = "2163db3ebe42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policy_rule",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("fund_entity_id", sa.String(length=36), nullable=False),
        sa.Column("rule_type", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("conditions_json", sa.JSON(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fund_entity_id"],
            ["fund_entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_policy_rule_fund", "policy_rule", ["fund_entity_id"], unique=False)
    op.create_index("ix_policy_rule_scope", "policy_rule", ["scope"], unique=False)
    op.create_table(
        "artifact_action",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artifact_type", sa.String(length=64), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_artifact_action_artifact",
        "artifact_action",
        ["artifact_type", "artifact_id"],
        unique=False,
    )
    op.create_index(
        "ix_artifact_action_pm_created", "artifact_action", ["pm_id", "created_at"], unique=False
    )
    op.create_table(
        "compliance_escalation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=True),
        sa.Column("fund_entity_id", sa.String(length=36), nullable=False),
        sa.Column("trigger_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reviewer_id", sa.String(length=36), nullable=True),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fund_entity_id"],
            ["fund_entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_compliance_escalation_fund_status",
        "compliance_escalation",
        ["fund_entity_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_compliance_escalation_pm_created",
        "compliance_escalation",
        ["pm_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "connector_config",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("credentials_encrypted", axe.security.encryption.EncryptedJSON(), nullable=False),
        sa.Column("schedule", sa.String(length=64), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_cursor", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pm_id", "source_type", name="uq_connector_config_pm_source"),
    )
    op.create_index(
        "ix_connector_config_pm_created", "connector_config", ["pm_id", "created_at"], unique=False
    )
    op.create_table(
        "decision_prompt",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=True),
        sa.Column("prompt_text", sa.Text(), nullable=True),
        sa.Column("options_json", sa.JSON(), nullable=False),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("deadline_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_decision_prompt_pm_created", "decision_prompt", ["pm_id", "created_at"], unique=False
    )
    op.create_table(
        "memory_citation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("linked_ticker", sa.String(length=32), nullable=True),
        sa.Column("linked_deal_id", sa.String(length=36), nullable=True),
        sa.Column("sentiment", sa.String(length=32), nullable=True),
        sa.Column("extracted_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_memory_citation_pm_created", "memory_citation", ["pm_id", "created_at"], unique=False
    )
    op.create_table(
        "model_trace",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=True),
        sa.Column("agent", sa.String(length=128), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("response_schema", sa.String(length=128), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("token_usage", sa.JSON(), nullable=False),
        sa.Column("citations_json", sa.JSON(), nullable=False),
        sa.Column("hallucination_score", sa.Float(), nullable=True),
        sa.Column("human_review_status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_model_trace_pm_created", "model_trace", ["pm_id", "created_at"], unique=False
    )
    op.create_index("ix_model_trace_prompt_hash", "model_trace", ["prompt_hash"], unique=False)
    op.create_table(
        "pm_peer_map",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("peer_email_or_slack_id", sa.String(length=255), nullable=False),
        sa.Column("peer_name", sa.String(length=255), nullable=True),
        sa.Column("relationship_type", sa.String(length=64), nullable=True),
        sa.Column("interaction_frequency", sa.String(length=32), nullable=True),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("trust_level", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pm_id", "peer_email_or_slack_id", name="uq_pm_peer_map_pm_peer"),
    )
    op.create_index(
        "ix_pm_peer_map_pm_created", "pm_peer_map", ["pm_id", "created_at"], unique=False
    )
    op.create_table(
        "pm_persona",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("writing_style_summary", sa.Text(), nullable=True),
        sa.Column("decision_triggers", sa.JSON(), nullable=False),
        sa.Column("peer_relationships_json", sa.JSON(), nullable=False),
        sa.Column("trusted_sources", sa.JSON(), nullable=False),
        sa.Column("confidence_language", sa.Text(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pm_id", name="uq_pm_persona_pm"),
    )
    op.create_index("ix_pm_persona_pm_created", "pm_persona", ["pm_id", "created_at"], unique=False)
    op.create_table(
        "raw_ingest",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("dedup_key", sa.String(length=255), nullable=True),
        sa.Column("raw_payload_json", sa.JSON(), nullable=False),
        sa.Column("extracted_signal_json", sa.JSON(), nullable=False),
        sa.Column("extracted_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_raw_ingest_content_hash", "raw_ingest", ["content_hash"], unique=False)
    op.create_index("ix_raw_ingest_pm_created", "raw_ingest", ["pm_id", "created_at"], unique=False)
    op.create_table(
        "specialist_signal",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("raw_ingest_id", sa.String(length=36), nullable=True),
        sa.Column("ticker", sa.String(length=32), nullable=True),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("specialist_agent", sa.String(length=64), nullable=False),
        sa.Column("signal_type", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("stance", sa.String(length=32), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.Column("assumptions_touched", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_specialist_signal_pm_created",
        "specialist_signal",
        ["pm_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_specialist_signal_raw_ingest", "specialist_signal", ["raw_ingest_id"], unique=False
    )
    op.add_column("audit_log", sa.Column("trace_id", sa.String(length=36), nullable=True))
    op.add_column("lp_updates", sa.Column("feedback_json", sa.JSON(), nullable=False))
    op.add_column("lp_updates", sa.Column("read_receipts_json", sa.JSON(), nullable=False))
    op.add_column("morning_briefs", sa.Column("decision_prompts_json", sa.JSON(), nullable=False))
    op.add_column("morning_briefs", sa.Column("actions_json", sa.JSON(), nullable=False))
    op.add_column("morning_briefs", sa.Column("citation_links_json", sa.JSON(), nullable=False))
    op.add_column("signal_log", sa.Column("source_id", sa.String(length=255), nullable=True))
    op.add_column(
        "signal_log", sa.Column("specialist_signal_id", sa.String(length=36), nullable=True)
    )
    op.add_column("signal_log", sa.Column("parent_signal_id", sa.String(length=36), nullable=True))
    op.add_column("signal_log", sa.Column("chain_id", sa.String(length=36), nullable=True))
    op.add_column(
        "thesis_versions", sa.Column("pm_persona_snapshot_id", sa.String(length=36), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("thesis_versions", "pm_persona_snapshot_id")
    op.drop_column("signal_log", "chain_id")
    op.drop_column("signal_log", "parent_signal_id")
    op.drop_column("signal_log", "specialist_signal_id")
    op.drop_column("signal_log", "source_id")
    op.drop_column("morning_briefs", "citation_links_json")
    op.drop_column("morning_briefs", "actions_json")
    op.drop_column("morning_briefs", "decision_prompts_json")
    op.drop_column("lp_updates", "read_receipts_json")
    op.drop_column("lp_updates", "feedback_json")
    op.drop_column("audit_log", "trace_id")
    op.drop_index("ix_specialist_signal_raw_ingest", table_name="specialist_signal")
    op.drop_index("ix_specialist_signal_pm_created", table_name="specialist_signal")
    op.drop_table("specialist_signal")
    op.drop_index("ix_raw_ingest_pm_created", table_name="raw_ingest")
    op.drop_index("ix_raw_ingest_content_hash", table_name="raw_ingest")
    op.drop_table("raw_ingest")
    op.drop_index("ix_pm_persona_pm_created", table_name="pm_persona")
    op.drop_table("pm_persona")
    op.drop_index("ix_pm_peer_map_pm_created", table_name="pm_peer_map")
    op.drop_table("pm_peer_map")
    op.drop_index("ix_model_trace_prompt_hash", table_name="model_trace")
    op.drop_index("ix_model_trace_pm_created", table_name="model_trace")
    op.drop_table("model_trace")
    op.drop_index("ix_memory_citation_pm_created", table_name="memory_citation")
    op.drop_table("memory_citation")
    op.drop_index("ix_decision_prompt_pm_created", table_name="decision_prompt")
    op.drop_table("decision_prompt")
    op.drop_index("ix_connector_config_pm_created", table_name="connector_config")
    op.drop_table("connector_config")
    op.drop_index("ix_compliance_escalation_pm_created", table_name="compliance_escalation")
    op.drop_index("ix_compliance_escalation_fund_status", table_name="compliance_escalation")
    op.drop_table("compliance_escalation")
    op.drop_index("ix_artifact_action_pm_created", table_name="artifact_action")
    op.drop_index("ix_artifact_action_artifact", table_name="artifact_action")
    op.drop_table("artifact_action")
    op.drop_index("ix_policy_rule_scope", table_name="policy_rule")
    op.drop_index("ix_policy_rule_fund", table_name="policy_rule")
    op.drop_table("policy_rule")
    # ### end Alembic commands ###
