"""initial_v2_1_schema

Revision ID: 13213e1afcdc
Revises:
Create Date: 2026-07-29 23:16:46.501733

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13213e1afcdc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deck_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("asset_class", sa.String(length=64), nullable=False),
        sa.Column("audience", sa.String(length=64), nullable=False),
        sa.Column("structure", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dedup_log",
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=True),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("content_hash"),
    )
    op.create_table(
        "fund_entities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("jurisdiction", sa.String(length=64), nullable=True),
        sa.Column("data_residency", sa.String(length=64), nullable=True),
        sa.Column("retention_years", sa.Integer(), nullable=False),
        sa.Column("mnpi_policy", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "investment_vehicles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("fund_entity_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("legal_entity", sa.String(length=255), nullable=True),
        sa.Column("strategy", sa.String(length=255), nullable=True),
        sa.Column("vintage", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("reporting_frequency", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fund_entity_id"],
            ["fund_entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pm_users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("fund_entity_id", sa.String(length=36), nullable=False),
        sa.Column("slack_user_id", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("compliance_approved", sa.Boolean(), nullable=False),
        sa.Column("onboarding_complete", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fund_entity_id"],
            ["fund_entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("slack_user_id"),
    )
    op.create_index("ix_pm_users_pm_created", "pm_users", ["id", "created_at"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=True),
        sa.Column("fund_entity_id", sa.String(length=36), nullable=True),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=36), nullable=True),
        sa.Column("before_state", sa.JSON(), nullable=False),
        sa.Column("after_state", sa.JSON(), nullable=False),
        sa.Column("source_ip", sa.String(length=45), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("client_timestamp", sa.DateTime(), nullable=True),
        sa.Column("server_timestamp", sa.DateTime(), nullable=False),
        sa.Column("retention_class", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fund_entity_id"],
            ["fund_entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_log_pm_created", "audit_log", ["pm_id", "created_at"], unique=False)
    op.create_table(
        "communication_archive",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("channel", sa.String(length=64), nullable=False),
        sa.Column("message_type", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_communication_archive_pm_created",
        "communication_archive",
        ["pm_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "deal_rooms",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("fund_entity_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("asset_class", sa.String(length=64), nullable=False),
        sa.Column("target_ticker_or_private_name", sa.String(length=255), nullable=True),
        sa.Column("cim_url", sa.String(length=2048), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fund_entity_id"],
            ["fund_entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_deal_rooms_pm_created", "deal_rooms", ["pm_id", "created_at"], unique=False)
    op.create_table(
        "deck_outputs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("source_ids", sa.JSON(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("export_url", sa.String(length=2048), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deck_outputs_pm_created", "deck_outputs", ["pm_id", "created_at"], unique=False
    )
    op.create_table(
        "lp_relationships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vehicle_id", sa.String(length=36), nullable=False),
        sa.Column("lp_name", sa.String(length=255), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("side_letter_flags", sa.JSON(), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["investment_vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lp_updates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vehicle_id", sa.String(length=36), nullable=False),
        sa.Column("quarter", sa.String(length=16), nullable=False),
        sa.Column("sections", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["investment_vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "morning_briefs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("sections", sa.JSON(), nullable=False),
        sa.Column("focus_one", sa.JSON(), nullable=False),
        sa.Column("catalyst_week", sa.JSON(), nullable=False),
        sa.Column("delivered_slack", sa.Boolean(), nullable=False),
        sa.Column("delivered_email", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pm_id", "date", name="uq_morning_briefs_pm_date"),
    )
    op.create_index(
        "ix_morning_briefs_pm_created", "morning_briefs", ["pm_id", "created_at"], unique=False
    )
    op.create_table(
        "pm_memory",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile", sa.JSON(), nullable=False),
        sa.Column("ticker_memories", sa.JSON(), nullable=False),
        sa.Column("interaction_patterns", sa.JSON(), nullable=False),
        sa.Column("fund_context", sa.JSON(), nullable=False),
        sa.Column("asset_class_memories", sa.JSON(), nullable=False),
        sa.Column("deal_memories", sa.JSON(), nullable=False),
        sa.Column("uncertainty_labels", sa.JSON(), nullable=False),
        sa.Column("last_synthesized_at", sa.DateTime(), nullable=False),
        sa.Column("synthesis_trigger", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pm_id", "version", name="uq_pm_memory_pm_version"),
    )
    op.create_index("ix_pm_memory_pm_created", "pm_memory", ["pm_id", "created_at"], unique=False)
    op.create_table(
        "pm_memory_cold_start",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("q1_hold_period", sa.Text(), nullable=True),
        sa.Column("q2_cutting_losers", sa.Text(), nullable=True),
        sa.Column("q3_edge", sa.Text(), nullable=True),
        sa.Column("q4_when_wrong", sa.Text(), nullable=True),
        sa.Column("q5_double_down", sa.Text(), nullable=True),
        sa.Column("synthesized", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pm_id"),
    )
    op.create_table(
        "pm_memory_corrections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("field", sa.String(length=128), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("corrected_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pm_memory_corrections_pm_created",
        "pm_memory_corrections",
        ["pm_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "pm_oauth_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expiry", sa.DateTime(), nullable=True),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pm_id", "provider", name="uq_pm_oauth_tokens_pm_provider"),
    )
    op.create_index(
        "ix_pm_oauth_tokens_pm_created", "pm_oauth_tokens", ["pm_id", "created_at"], unique=False
    )
    op.create_table(
        "pm_quiet_hours",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("start_time", sa.String(length=8), nullable=False),
        sa.Column("end_time", sa.String(length=8), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("override_keywords", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pm_id"),
    )
    op.create_table(
        "retry_queue",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=True),
        sa.Column("task_type", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_attempted_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("broker_attempted", sa.Boolean(), nullable=False),
        sa.Column("dead_letter_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_retry_queue_pm_created", "retry_queue", ["pm_id", "created_at"], unique=False
    )
    op.create_table(
        "signal_log",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=True),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("extracted_signal", sa.JSON(), nullable=False),
        sa.Column("citation", sa.JSON(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("thesis_assumption_id", sa.String(length=64), nullable=True),
        sa.Column("stance", sa.String(length=32), nullable=True),
        sa.Column("mnpi_flag", sa.Boolean(), nullable=False),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("alerted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_signal_log_content_hash", "signal_log", ["content_hash"], unique=False)
    op.create_index("ix_signal_log_pm_created", "signal_log", ["pm_id", "created_at"], unique=False)
    op.create_table(
        "thesis_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("asset_class", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("bull_case", sa.Text(), nullable=True),
        sa.Column("bear_case", sa.Text(), nullable=True),
        sa.Column("key_assumptions", sa.JSON(), nullable=False),
        sa.Column("catalysts", sa.JSON(), nullable=False),
        sa.Column("conviction", sa.Integer(), nullable=True),
        sa.Column("unresolved_risks", sa.JSON(), nullable=False),
        sa.Column("fund_entity_id", sa.String(length=36), nullable=False),
        sa.Column("mnpi_flag", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fund_entity_id"],
            ["fund_entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pm_id", "ticker", "version", name="uq_thesis_versions_pm_ticker_version"
        ),
    )
    op.create_index(
        "ix_thesis_versions_pm_created", "thesis_versions", ["pm_id", "created_at"], unique=False
    )
    op.create_table(
        "ticker_registry",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("asset_class", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("position_size_bucket", sa.String(length=32), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=False),
        sa.Column("last_thesis_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pm_id", "ticker", name="uq_ticker_registry_pm_ticker"),
    )
    op.create_index(
        "ix_ticker_registry_pm_created", "ticker_registry", ["pm_id", "claimed_at"], unique=False
    )
    op.create_table(
        "deal_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deal_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("file_path", sa.String(length=2048), nullable=True),
        sa.Column("content_url", sa.String(length=2048), nullable=True),
        sa.Column("extracted_entities", sa.JSON(), nullable=False),
        sa.Column("ingestion_status", sa.String(length=32), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deal_rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deal_thesis_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deal_id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("checkpoints", sa.JSON(), nullable=False),
        sa.Column("bull_case", sa.Text(), nullable=True),
        sa.Column("bear_case", sa.Text(), nullable=True),
        sa.Column("key_assumptions", sa.JSON(), nullable=False),
        sa.Column("risks", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deal_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deal_id", "version", name="uq_deal_thesis_versions_deal_version"),
    )
    op.create_index(
        "ix_deal_thesis_versions_pm_created",
        "deal_thesis_versions",
        ["pm_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "meeting_summaries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=True),
        sa.Column("deal_id", sa.String(length=36), nullable=True),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("guidance_changes", sa.JSON(), nullable=False),
        sa.Column("commitments", sa.JSON(), nullable=False),
        sa.Column("tone_signals", sa.JSON(), nullable=False),
        sa.Column("thesis_conflicts", sa.JSON(), nullable=False),
        sa.Column("mnpi_flag", sa.Boolean(), nullable=False),
        sa.Column("speaker_roles", sa.JSON(), nullable=False),
        sa.Column("citation_timestamps", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deal_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_meeting_summaries_pm_created",
        "meeting_summaries",
        ["pm_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "signal_feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("signal_id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("reaction", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signal_log.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_signal_feedback_pm_created", "signal_feedback", ["pm_id", "created_at"], unique=False
    )
    op.create_table(
        "sparring_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=True),
        sa.Column("deal_id", sa.String(length=36), nullable=True),
        sa.Column("thesis_version_id", sa.String(length=36), nullable=True),
        sa.Column("input_thesis", sa.Text(), nullable=True),
        sa.Column("bear_case", sa.JSON(), nullable=False),
        sa.Column("contradicting_signals", sa.JSON(), nullable=False),
        sa.Column("break_conditions", sa.JSON(), nullable=False),
        sa.Column("citation_list", sa.JSON(), nullable=False),
        sa.Column("pm_response", sa.Text(), nullable=True),
        sa.Column("accepted_challenges", sa.JSON(), nullable=False),
        sa.Column("output_format", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deal_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thesis_version_id"],
            ["thesis_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sparring_sessions_pm_created",
        "sparring_sessions",
        ["pm_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "thesis_post_mortems",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("thesis_version_id", sa.String(length=36), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("broken_assumption_id", sa.String(length=64), nullable=True),
        sa.Column("ignored_signal_id", sa.String(length=36), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["thesis_version_id"],
            ["thesis_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "thesis_tests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("thesis_version_id", sa.String(length=36), nullable=False),
        sa.Column("assumption_id", sa.String(length=64), nullable=True),
        sa.Column("test_statement", sa.Text(), nullable=False),
        sa.Column("pass_criteria", sa.Text(), nullable=True),
        sa.Column("fail_criteria", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_evaluated_at", sa.DateTime(), nullable=True),
        sa.Column("evidence_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["thesis_version_id"],
            ["thesis_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "underwriting_checklists",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deal_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("evidence_url", sa.String(length=2048), nullable=True),
        sa.Column("answered_by", sa.String(length=36), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deal_rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "underwriting_scenarios",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deal_id", sa.String(length=36), nullable=False),
        sa.Column("scenario_name", sa.String(length=255), nullable=False),
        sa.Column("assumptions", sa.JSON(), nullable=False),
        sa.Column("output_metrics", sa.JSON(), nullable=False),
        sa.Column("probability_weight", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deal_rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "thesis_test_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("test_id", sa.String(length=36), nullable=False),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["thesis_tests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thesis_test_results")
    op.drop_table("underwriting_scenarios")
    op.drop_table("underwriting_checklists")
    op.drop_table("thesis_tests")
    op.drop_table("thesis_post_mortems")
    op.drop_index("ix_sparring_sessions_pm_created", table_name="sparring_sessions")
    op.drop_table("sparring_sessions")
    op.drop_index("ix_signal_feedback_pm_created", table_name="signal_feedback")
    op.drop_table("signal_feedback")
    op.drop_index("ix_meeting_summaries_pm_created", table_name="meeting_summaries")
    op.drop_table("meeting_summaries")
    op.drop_index("ix_deal_thesis_versions_pm_created", table_name="deal_thesis_versions")
    op.drop_table("deal_thesis_versions")
    op.drop_table("deal_documents")
    op.drop_index("ix_ticker_registry_pm_created", table_name="ticker_registry")
    op.drop_table("ticker_registry")
    op.drop_index("ix_thesis_versions_pm_created", table_name="thesis_versions")
    op.drop_table("thesis_versions")
    op.drop_index("ix_signal_log_pm_created", table_name="signal_log")
    op.drop_index("ix_signal_log_content_hash", table_name="signal_log")
    op.drop_table("signal_log")
    op.drop_index("ix_retry_queue_pm_created", table_name="retry_queue")
    op.drop_table("retry_queue")
    op.drop_table("pm_quiet_hours")
    op.drop_index("ix_pm_oauth_tokens_pm_created", table_name="pm_oauth_tokens")
    op.drop_table("pm_oauth_tokens")
    op.drop_index("ix_pm_memory_corrections_pm_created", table_name="pm_memory_corrections")
    op.drop_table("pm_memory_corrections")
    op.drop_table("pm_memory_cold_start")
    op.drop_index("ix_pm_memory_pm_created", table_name="pm_memory")
    op.drop_table("pm_memory")
    op.drop_index("ix_morning_briefs_pm_created", table_name="morning_briefs")
    op.drop_table("morning_briefs")
    op.drop_table("lp_updates")
    op.drop_table("lp_relationships")
    op.drop_index("ix_deck_outputs_pm_created", table_name="deck_outputs")
    op.drop_table("deck_outputs")
    op.drop_index("ix_deal_rooms_pm_created", table_name="deal_rooms")
    op.drop_table("deal_rooms")
    op.drop_index("ix_communication_archive_pm_created", table_name="communication_archive")
    op.drop_table("communication_archive")
    op.drop_index("ix_audit_log_pm_created", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("ix_pm_users_pm_created", table_name="pm_users")
    op.drop_table("pm_users")
    op.drop_table("investment_vehicles")
    op.drop_table("fund_entities")
    op.drop_table("dedup_log")
    op.drop_table("deck_templates")
    op.drop_table("corporate_actions")
    # ### end Alembic commands ###
