"""add_mnpi_guardrail_columns

Revision ID: 14ca6f51c1e8
Revises: 8ce0784d6785
Create Date: 2026-08-14 01:04:56.838162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '14ca6f51c1e8'
down_revision: Union[str, None] = '8ce0784d6785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mnpi_review_queue', sa.Column('guardrail_result_json', sa.JSON(), nullable=True))
    op.add_column('mnpi_review_queue', sa.Column('guardrail_escalation_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mnpi_review_queue', 'guardrail_escalation_id')
    op.drop_column('mnpi_review_queue', 'guardrail_result_json')
    # ### end Alembic commands ###
