"""add_deal_document_file_size_mime_type

Revision ID: 2163150b18d8
Revises: 414741cba10e
Create Date: 2026-08-04 18:20:47.216735

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2163150b18d8"
down_revision: str | None = "414741cba10e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deal_documents", sa.Column("file_size", sa.Integer(), nullable=True))
    op.add_column("deal_documents", sa.Column("mime_type", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deal_documents", "mime_type")
    op.drop_column("deal_documents", "file_size")
    # ### end Alembic commands ###
