"""add broken assumption tracking

Revision ID: 2827983cf810
Revises: be01ebb59012
Create Date: 2026-07-31 18:06:51.218714

"""

from collections.abc import Sequence

import sqlalchemy as sa

import axe.security.encryption
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2827983cf810"
down_revision: str | None = "be01ebb59012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalyst_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("event_time", sa.String(length=16), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("relevance_tags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalyst_events_event_date"), "catalyst_events", ["event_date"], unique=False
    )
    op.create_index(op.f("ix_catalyst_events_ticker"), "catalyst_events", ["ticker"], unique=False)
    op.create_index(
        "ix_catalyst_events_ticker_date", "catalyst_events", ["ticker", "event_date"], unique=False
    )
    op.create_table(
        "brief_replies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("brief_id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("slack_thread_ts", sa.String(length=32), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("intent", sa.String(length=32), nullable=True),
        sa.Column("action_taken", sa.Text(), nullable=True),
        sa.Column("action_payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brief_id"],
            ["morning_briefs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_brief_replies_brief_created", "brief_replies", ["brief_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_brief_replies_brief_id"), "brief_replies", ["brief_id"], unique=False)
    op.create_table(
        "broken_assumptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pm_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("assumption_id", sa.String(length=64), nullable=False),
        sa.Column("signal_id", sa.String(length=36), nullable=True),
        sa.Column("alerted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pm_id"],
            ["pm_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signal_log.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pm_id", "ticker", "assumption_id", name="uq_broken_assumptions_pm_ticker_assumption"
        ),
    )
    op.create_index(
        "ix_broken_assumptions_pm_alerted",
        "broken_assumptions",
        ["pm_id", "alerted_at"],
        unique=False,
    )
    op.add_column(
        "pm_oauth_tokens",
        sa.Column("token_payload", axe.security.encryption.EncryptedJSON(), nullable=False),
    )
    op.drop_column("pm_oauth_tokens", "refresh_token")
    op.drop_column("pm_oauth_tokens", "access_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pm_oauth_tokens", sa.Column("access_token", sa.TEXT(), nullable=False))
    op.add_column("pm_oauth_tokens", sa.Column("refresh_token", sa.TEXT(), nullable=True))
    op.drop_column("pm_oauth_tokens", "token_payload")
    op.drop_index("ix_broken_assumptions_pm_alerted", table_name="broken_assumptions")
    op.drop_table("broken_assumptions")
    op.drop_index(op.f("ix_brief_replies_brief_id"), table_name="brief_replies")
    op.drop_index("ix_brief_replies_brief_created", table_name="brief_replies")
    op.drop_table("brief_replies")
    op.drop_index("ix_catalyst_events_ticker_date", table_name="catalyst_events")
    op.drop_index(op.f("ix_catalyst_events_ticker"), table_name="catalyst_events")
    op.drop_index(op.f("ix_catalyst_events_event_date"), table_name="catalyst_events")
    op.drop_table("catalyst_events")
    # ### end Alembic commands ###
