"""add_underwriting_checklist_required_and_confidence

Revision ID: 3e204c7c3579
Revises: 2163150b18d8
Create Date: 2026-08-04 22:08:25.787072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e204c7c3579'
down_revision: Union[str, None] = '2163150b18d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('underwriting_checklists', sa.Column('required', sa.Boolean(), nullable=False))
    op.add_column('underwriting_checklists', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.add_column('underwriting_scenarios', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('underwriting_scenarios', 'confidence')
    op.drop_column('underwriting_checklists', 'sort_order')
    op.drop_column('underwriting_checklists', 'required')
    # ### end Alembic commands ###
