"""add retention_exempt and deleted_at columns

Revision ID: 414741cba10e
Revises: add_mnpi_review_queue
Create Date: 2026-08-02 23:53:12.634650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414741cba10e'
down_revision: Union[str, None] = 'add_mnpi_review_queue'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication_archive', sa.Column('retention_exempt', sa.Boolean(), nullable=False))
    op.add_column('communication_archive', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('meeting_summaries', sa.Column('retention_exempt', sa.Boolean(), nullable=False))
    op.add_column('meeting_summaries', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('morning_briefs', sa.Column('retention_exempt', sa.Boolean(), nullable=False))
    op.add_column('morning_briefs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('signal_log', sa.Column('retention_exempt', sa.Boolean(), nullable=False))
    op.add_column('signal_log', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('sparring_sessions', sa.Column('retention_exempt', sa.Boolean(), nullable=False))
    op.add_column('sparring_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('thesis_post_mortems', sa.Column('retention_exempt', sa.Boolean(), nullable=False))
    op.add_column('thesis_post_mortems', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('thesis_test_results', sa.Column('retention_exempt', sa.Boolean(), nullable=False))
    op.add_column('thesis_test_results', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('thesis_test_results', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('thesis_versions', sa.Column('retention_exempt', sa.Boolean(), nullable=False))
    op.add_column('thesis_versions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thesis_versions', 'deleted_at')
    op.drop_column('thesis_versions', 'retention_exempt')
    op.drop_column('thesis_test_results', 'deleted_at')
    op.drop_column('thesis_test_results', 'created_at')
    op.drop_column('thesis_test_results', 'retention_exempt')
    op.drop_column('thesis_post_mortems', 'deleted_at')
    op.drop_column('thesis_post_mortems', 'retention_exempt')
    op.drop_column('sparring_sessions', 'deleted_at')
    op.drop_column('sparring_sessions', 'retention_exempt')
    op.drop_column('signal_log', 'deleted_at')
    op.drop_column('signal_log', 'retention_exempt')
    op.drop_column('morning_briefs', 'deleted_at')
    op.drop_column('morning_briefs', 'retention_exempt')
    op.drop_column('meeting_summaries', 'deleted_at')
    op.drop_column('meeting_summaries', 'retention_exempt')
    op.drop_column('communication_archive', 'deleted_at')
    op.drop_column('communication_archive', 'retention_exempt')
    # ### end Alembic commands ###
