"""add_agent_messages

Revision ID: adf8ba209e26
Revises: 05bee0ba72de
Create Date: 2026-08-09 22:02:21.860980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'adf8ba209e26'
down_revision: Union[str, None] = '05bee0ba72de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_agent', sa.String(length=128), nullable=False),
    sa.Column('recipient_agent', sa.String(length=128), nullable=True),
    sa.Column('sender_pm_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_pm_id', sa.String(length=36), nullable=True),
    sa.Column('fund_entity_id', sa.String(length=36), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('allowed_other_pm_ids', sa.JSON(), nullable=False),
    sa.Column('required_confidence', sa.Float(), nullable=False),
    sa.Column('requires_decision', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_entity_id'], ['fund_entities.id'], ),
    sa.ForeignKeyConstraint(['recipient_pm_id'], ['pm_users.id'], ),
    sa.ForeignKeyConstraint(['sender_pm_id'], ['pm_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_messages_fund', 'agent_messages', ['fund_entity_id'], unique=False)
    op.create_index('ix_agent_messages_pm_created', 'agent_messages', ['sender_pm_id', 'created_at'], unique=False)
    op.create_index('ix_agent_messages_recipient', 'agent_messages', ['recipient_pm_id', 'created_at'], unique=False)
    op.alter_column('communication_archive', 'archive_metadata',
               existing_type=sqlite.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communication_archive', 'archive_metadata',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.drop_index('ix_agent_messages_recipient', table_name='agent_messages')
    op.drop_index('ix_agent_messages_pm_created', table_name='agent_messages')
    op.drop_index('ix_agent_messages_fund', table_name='agent_messages')
    op.drop_table('agent_messages')
    # ### end Alembic commands ###
